# Generated by Django 2.1.1 on 2018-10-15 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20181016_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('leaderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TeamContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.FloatField(default=0.0)),
                ('code', models.FloatField(default=0.0)),
                ('resource', models.FloatField(default=0.0)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writtenDate', models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 13, 11, 827145, tzinfo=utc), verbose_name='date registered')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
    ]
