# Generated by Django 2.1.2 on 2018-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcontribution',
            name='teamId',
        ),
        migrations.RemoveField(
            model_name='teamnotice',
            name='teamId',
        ),
        migrations.RemoveField(
            model_name='teamnotice',
            name='writer',
        ),
        migrations.DeleteModel(
            name='TeamContribution',
        ),
        migrations.DeleteModel(
            name='TeamNotice',
        ),
    ]
