# Generated by Django 2.1.1 on 2018-10-29 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181030_0623'),
        ('teamproject', '0004_remove_team_peoplenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.FloatField(default=0.0)),
                ('code', models.FloatField(default=0.0)),
                ('resource', models.FloatField(default=0.0)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writtenDate', models.DateTimeField(default=datetime.datetime(2018, 10, 29, 21, 23, 53, 398596, tzinfo=utc), verbose_name='date registered')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
    ]
