# Generated by Django 2.1.2 on 2018-10-29 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0008_auto_20181030_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamnotice',
            name='writtenDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 22, 36, 38, 520864, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
