# Generated by Django 2.1.2 on 2018-11-05 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0008_auto_20181030_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamnotice',
            name='writtenDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 18, 20, 17, 680542, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
