# Generated by Django 2.1.2 on 2018-11-05 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181106_0207'),
        ('teamproject', '0009_auto_20181030_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendedDate', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 7, 2, 168373, tzinfo=utc), verbose_name='data sended')),
                ('chatMsg', models.TextField()),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Member')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='teamnotice',
            name='writtenDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 7, 2, 165373, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
