# Generated by Django 2.1.2 on 2018-11-05 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0010_auto_20181106_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchat',
            name='sendedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 27, 41, 296457, tzinfo=utc), verbose_name='data sended'),
        ),
        migrations.AlterField(
            model_name='teamnotice',
            name='writtenDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 27, 41, 293435, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
