# Generated by Django 2.1.2 on 2018-11-05 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0012_auto_20181106_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchat',
            name='sendedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 38, 13, 652647, tzinfo=utc), verbose_name='data sended'),
        ),
        migrations.AlterField(
            model_name='teamnotice',
            name='writtenDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 38, 13, 649689, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
