# Generated by Django 2.1.3 on 2018-11-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teamproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='teamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamproject.Team'),
        ),
    ]
