# Generated by Django 2.1.1 on 2018-10-15 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='registerDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 13, 11, 829145, tzinfo=utc), verbose_name='date registered'),
        ),
        migrations.AddField(
            model_name='participate',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
    ]
