# Generated by Django 2.1.3 on 2018-11-26 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_participate_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registerDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 25, 49, 629435, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
