# Generated by Django 2.1.1 on 2018-10-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181016_0613'),
        ('teamproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='teamId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team'),
        ),
    ]
