# Generated by Django 2.1.2 on 2018-10-27 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181016_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registerDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 9, 1, 46, 376122, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
