# Generated by Django 2.1.2 on 2018-11-05 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181106_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registerDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 17, 27, 41, 308830, tzinfo=utc), verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='hackId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.HackathonInformation'),
        ),
    ]
