# Generated by Django 2.1.2 on 2018-10-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hackathonInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('applyDate_start', models.DateField(help_text='Please use the following format : <em>YYYY-MM-DD</em>')),
                ('applyTime_start', models.TimeField(help_text='Please use the following format : <em>12:00:00</em>')),
                ('applyDate_end', models.DateField(help_text='Please use the following format : <em>YYYY-MM-DD</em>')),
                ('applyTime_end', models.TimeField(help_text='Please use the following format : <em>12:00:00</em>')),
                ('peopleNum', models.IntegerField()),
                ('memberNum_max', models.IntegerField()),
                ('memberNum_min', models.IntegerField()),
                ('selectMatching', models.IntegerField(choices=[(0, '자율선택'), (1, '랜덤매칭')])),
                ('Images', models.FileField(blank=True, upload_to='./Hackathon/static/uploads')),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
