# Generated by Django 2.1.3 on 2018-11-26 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacknotice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 24, 47, 432240, tzinfo=utc)),
        ),
    ]
