# Generated by Django 2.1.2 on 2018-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.FileField(blank=True, upload_to='./hackathon/static/uploads'),
        ),
    ]
