# Generated by Django 2.1.2 on 2018-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20181013_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathoninformation',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
