# Generated by Django 2.1.2 on 2018-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathoninformation_applynum'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathoninformation',
            name='hackathonHost',
            field=models.CharField(default='wkdthf21', max_length=100),
        ),
    ]
