# Generated by Django 2.1.2 on 2018-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_hackathoninformation_hackathonhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(default='wkdthf21', max_length=100)),
                ('hackathonID', models.IntegerField(default=0)),
            ],
        ),
    ]
