# Generated by Django 2.1.2 on 2018-10-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_participation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participation',
            new_name='participate',
        ),
    ]
