# Generated by Django 2.1.2 on 2018-10-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20181013_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='hackathonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathonInformation'),
        ),
    ]
