# Generated by Django 2.1.2 on 2018-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20181013_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.ImageField(upload_to='./hackathon/static/uploads'),
        ),
    ]
