# Generated by Django 2.1.2 on 2018-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20181013_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.FileField(upload_to='hackathon/static/uploads'),
        ),
    ]
