# Generated by Django 2.1.2 on 2018-10-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_auto_20181013_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.FileField(upload_to='./hackathon/static/uploads'),
        ),
    ]
