# Generated by Django 2.1.2 on 2018-10-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_auto_20181013_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.FileField(upload_to='./hackathon/static/uploads/%Y/%m/%d'),
        ),
    ]
