# Generated by Django 2.1.2 on 2018-10-14 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_auto_20181013_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathoninformation',
            name='contestDate_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Please use the following format : <em>YYYY-MM-DD</em>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathoninformation',
            name='contestDate_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Please use the following format : <em>YYYY-MM-DD</em>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathoninformation',
            name='contestTime_end',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, help_text='Please use the following format : <em>12:00:00</em>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathoninformation',
            name='contestTime_start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, help_text='Please use the following format : <em>12:00:00</em>'),
            preserve_default=False,
        ),
    ]
