# Generated by Django 2.1.2 on 2018-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_auto_20181014_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempLoginInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeberID', models.CharField(default='yedoriii', max_length=100)),
            ],
        ),
    ]
