# Generated by Django 2.1.2 on 2018-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0015_templogininformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.ImageField(upload_to='./hackathon/static/uploads/%Y/%m/%d'),
        ),
    ]
