# Generated by Django 2.1.2 on 2018-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0016_auto_20181016_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='Images',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
