# Generated by Django 2.1.2 on 2018-10-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20181016_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='hackathonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.HackathonInformation'),
        ),
    ]
