# Generated by Django 2.1.2 on 2018-10-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_auto_20181027_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoninformation',
            name='hackathonHost',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='participate',
            name='hackathonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.HackathonInformation'),
        ),
    ]
