# Generated by Django 2.1.2 on 2018-10-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0019_auto_20181028_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='hackathonID',
        ),
        migrations.DeleteModel(
            name='participate',
        ),
    ]
