# Generated by Django 2.1.2 on 2018-10-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0020_auto_20181028_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempLoginInformation',
        ),
    ]
