# Generated by Django 2.1.3 on 2018-12-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abusing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('commitId', models.CharField(max_length=200)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
    ]
